# Generated by Wisp's apply_colors.sh (matugen) — do not edit.
# Terminal-agnostic recolor via OSC escape sequences (works in kitty,
# alacritty, foot, wezterm, and most other modern terminal emulators —
# unlike scripts/templates/kitty-colors.conf, which only kitty understands).
# Source this file from your shell's init (e.g. fish's config.fish) to
# recolor whatever terminal that shell happens to be running in, on every
# new shell/tab. Same 16-color role mapping as kitty-colors.conf, so kitty's
# native theme and this OSC recolor always agree.
#
# `printf` is used (not `echo`) because it's a portable builtin in both
# POSIX shells and fish, and interprets \033/\a escapes the same way in both.
# Terminated with BEL (\a), not ST (ESC \) — matugen's template renderer
# collapses a literal `\\` in the source template down to a single `\`, which
# left a lone trailing backslash right before the closing quote; fish's
# parser then reads that as an escaped-quote (`\'`) instead of the string
# terminator and fails with "quotes are not balanced". BEL is a single
# character, sidesteps the whole issue, and is just as widely supported.

printf '\033]10;{{colors.on_surface.default.hex}}\a'
printf '\033]11;{{colors.surface.default.hex}}\a'
printf '\033]12;{{colors.primary.default.hex}}\a'

printf '\033]4;0;{{colors.surface_variant.default.hex}}\a'
printf '\033]4;8;{{colors.outline.default.hex}}\a'
printf '\033]4;1;{{colors.error.default.hex}}\a'
printf '\033]4;9;{{colors.error_container.default.hex}}\a'
printf '\033]4;2;{{colors.primary.default.hex}}\a'
printf '\033]4;10;{{colors.primary_fixed.default.hex}}\a'
printf '\033]4;3;{{colors.tertiary.default.hex}}\a'
printf '\033]4;11;{{colors.tertiary_fixed.default.hex}}\a'
printf '\033]4;4;{{colors.secondary.default.hex}}\a'
printf '\033]4;12;{{colors.secondary_fixed.default.hex}}\a'
printf '\033]4;5;{{colors.primary_container.default.hex}}\a'
printf '\033]4;13;{{colors.inverse_primary.default.hex}}\a'
printf '\033]4;6;{{colors.secondary_container.default.hex}}\a'
printf '\033]4;14;{{colors.tertiary_container.default.hex}}\a'
printf '\033]4;7;{{colors.on_surface_variant.default.hex}}\a'
printf '\033]4;15;{{colors.on_surface.default.hex}}\a'
