pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "."

// Color source of truth. Two layers:
//   1. Static Catppuccin Mocha fallback (always available).
//   2. Dynamic Material You palette from colors.json (generated by
//      scripts/apply_colors.sh via matugen), active only when
//      Settings.conf.colors.dynamicEnabled — flip the switch and every
//      bound color in the shell animates to the wallpaper palette.
// Semantic accents (green/peach/blue/yellow) stay static: M3 has no
// success/warning roles and gauges/weather need stable hue meaning.
Singleton {
    id: theme

    // Palette from colors.json; null until loaded
    property var m3: null
    property string dynWallpaper: ""
    readonly property bool dynamicActive: Settings.conf.colors.dynamicEnabled && m3 !== null

    function c(role, fallback) {
        return dynamicActive && m3[role] !== undefined ? m3[role] : fallback;
    }

    property color background: c("background", "#1e1e2e")
    property color surface: c("surface_container", "#313244")
    property color primary: c("primary", "#cba6f7")
    property color colorOnPrimary: c("on_primary", "#11111b")
    // Border/separator colour. Was #45475a (Catppuccin surface1) — the same
    // value as `surface0` below, i.e. a tonal *step* doing double duty as a
    // *border*. Measured at APCA Lc 10.4 on background and 5.4 on surface,
    // against a ≥30 target for non-text UI: the shell's 44 one-pixel borders
    // were effectively invisible, adding visual noise without separating
    // anything. Raised to Catppuccin overlay1, which measures Lc 36.2/31.2 and
    // clears the target on both surfaces. See DESIGN.md finding A3.
    property color outline: c("outline_variant", "#7f849c")
    property color text: c("on_background", "#cdd6f4")
    // Secondary text. Was #a6adc8 (subtext0) at Lc 57.3/52.3/45.8 on
    // background/surface/surface0 — well under APCA's ≥75 body-text target at
    // the 10–13px sizes it is actually used at. Raised to Catppuccin subtext1.
    //
    // Honest limitation: ≥75 is NOT reachable here. Even promoting this to the
    // full `text` colour only measures 69.5 on surface0, and would erase the
    // primary/secondary distinction entirely. On a dark palette you cannot have
    // both "visibly dimmer than primary text" and Lc ≥75. The real remedy is
    // the other half of the pair — stop setting this colour at 10–11px, so the
    // ≥45 large/bold target applies instead (DESIGN.md finding A4).
    property color subtext0: c("on_surface_variant", "#bac2de")
    property color surface0: c("surface_container_highest", "#45475a")
    property color red: c("error", "#f38ba8")
    property color green: "#a6e3a1"
    property color peach: "#fab387"
    property color blue: "#89b4fa"
    property color yellow: "#f9e2af"
    // Discord brand blurple — fixed, not palette-derived, on purpose: the
    // island's Discord lane is a brand badge, same reasoning as osu's pink.
    property color blurple: "#5865f2"

    // Translucent variant of background for the floating pill / settings window,
    // driven by Settings.conf.colors.panelAlpha — kept separate from `background`
    // since that property is also used as an opaque text/icon contrast color
    // all over the shell (e.g. icon glyphs on a colored fill).
    property color panelBackground: Qt.rgba(background.r, background.g, background.b, Settings.conf.colors.panelAlpha)
    Behavior on panelBackground { ColorAnimation { duration: 250; easing.type: Easing.OutCubic } }

    Behavior on background { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }
    Behavior on surface { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }
    Behavior on primary { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }
    Behavior on colorOnPrimary { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }
    Behavior on outline { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }
    Behavior on text { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }
    Behavior on subtext0 { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }
    Behavior on surface0 { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }
    Behavior on red { ColorAnimation { duration: 600; easing.type: Easing.OutCubic } }

    // ── Fonts ──
    // Picked from a preference list at startup rather than hardcoded, because
    // a missing font fails *silently and invisibly*: Qt resolves an unknown
    // family through fontconfig to whatever the default sans is, so the text
    // still renders and nothing warns. That is exactly how this project shipped
    // 75 hardcoded references to "Iosevka Nerd Font" — a font never installed
    // here — with the icons only rendering by accident, via fontconfig's
    // per-glyph fallback landing on some other Nerd Font. Resolving explicitly
    // means a missing font degrades to a *chosen* second choice, and the
    // resolution is inspectable instead of guessed.
    function pickFont(candidates, fallback) {
        const installed = Qt.fontFamilies();
        for (const c of candidates) {
            if (installed.indexOf(c) !== -1) return c;
        }
        console.warn("Theme: none of", JSON.stringify(candidates), "installed; falling back to", fallback);
        return fallback;
    }

    // Body/UI text. Google Sans Flex is a variable font (one file covers
    // tooltip-size to headline-size cleanly) and is what both of the most
    // polished reference shells (ii-dots, caelestia-dots) use as their sans.
    readonly property string fontFamily: pickFont(
        ["Google Sans Flex", "Inter", "Rubik", "Noto Sans"], "sans-serif")

    // Nerd Font glyphs. Must be a font that actually carries the Nerd glyph
    // ranges — the whole point of the resolution above.
    readonly property string fontIcon: pickFont(
        ["JetBrainsMono Nerd Font", "Symbols Nerd Font", "FantasqueSansM Nerd Font",
         "MesloLGS Nerd Font", "Iosevka Nerd Font"], "monospace")

    // Monospace (keybind chips, action ids, config paths).
    readonly property string fontMono: pickFont(
        ["JetBrainsMono Nerd Font", "JetBrains Mono", "Noto Sans Mono"], "monospace")

    Component.onCompleted: console.log("Theme fonts -> text:", fontFamily, "| icon:", fontIcon, "| mono:", fontMono)

    readonly property int animFast: 150
    readonly property int animSlow: 350

    // Easing curve for fluid bounce
    readonly property var easeSpring: Easing.OutBack
    readonly property var easeOut: Easing.OutCubic

    FileView {
        id: colorsFile
        path: Paths.colorsFile
        watchChanges: true
        onFileChanged: reload()
        onLoaded: {
            try {
                const doc = JSON.parse(text());
                theme.m3 = doc.colors;
                theme.dynWallpaper = doc.wallpaper || "";
            } catch (e) { theme.m3 = null; }
        }
        onLoadFailed: theme.m3 = null
    }
}
