import sys
import json
import os

def main():
    if len(sys.argv) < 3:
        print("Usage: write_custom_windowrules.py <hypr_config_dir> <json_data>")
        sys.exit(1)

    hypr_config_dir = sys.argv[1]
    json_data = sys.argv[2]
    out_file = os.path.join(hypr_config_dir, "windowrules_custom.lua")

    try:
        rules = json.loads(json_data)
    except json.JSONDecodeError:
        print("Invalid JSON data")
        sys.exit(1)

    lines = [
        "-- Auto-generated by wisp-shell Settings",
        "-- Do not edit manually. Add rules via Settings > Window Rules.",
        ""
    ]

    for rule in rules:
        match_class = rule.get("match", "")
        if not match_class:
            continue
        
        # Build match block
        match_str = f'match = {{ class = "{match_class}" }}'
        
        # Build rules block
        rule_pairs = []
        for key, val in rule.get("rules", {}).items():
            if isinstance(val, bool):
                rule_pairs.append(f'{key} = {"true" if val else "false"}')
            elif isinstance(val, str):
                rule_pairs.append(f'{key} = "{val}"')
            elif isinstance(val, int) or isinstance(val, float):
                rule_pairs.append(f'{key} = {val}')
                
        if not rule_pairs:
            continue
            
        rules_str = ", ".join(rule_pairs)
        lines.append(f'hl.window_rule({{ {match_str}, {rules_str} }})')

    lines.append("")

    with open(out_file, "w") as f:
        f.write("\n".join(lines))

if __name__ == "__main__":
    main()
